project:
  type: website
  pre-render: 
    - typst compile img/src/onion-concrete.typ img/onion-concrete.svg

website:
  title: "force-eoap"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    respect-user-color-scheme: true
    css: styles.css
    toc: true

