project:
  type: website
  pre-render: 
    - typst compile img/src/onion-concrete.typ img/onion-concrete.svg

website:
  title: "FORCE on CDSE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: guide/intro.qmd
        text: Guide
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Guide"
        href: guide/intro.qmd
        contents:
          - guide/processes.qmd
          - guide/query.qmd
          - guide/level2.qmd
          - guide/tsa.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    respect-user-color-scheme: true
    css: styles.css
    toc: true

