# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "latest"
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    install:
      - pixi install --manifest-path docs/pixi.toml
    build:
      html:
        - cd docs/force-eoap && pixi run quarto render docs/force-eoap --output-dir $READTHEDOCS_OUTPUT/html

