from collections.abc import Iterable
from pathlib import Path
from typing import Union, List, Optional

import pystac
import rasterio
import shapely
from rasterio import warp


class ForceDatacubeStore:
    DATACUBE_DEFINITION_FILENAME: str = "datacube-definition.prj"
    TARGET_BOUNDS_CRS: str = "EPSG:4326"
    DENSIFY_POINTS_DEFAULT: int = 21

    _data_cube_root: Path
    projection_wkt: str
    grid_origin_lon: float
    grid_origin_lat: float
    grid_origin_x: float
    grid_origin_y: float
    tile_size: int
    block_size: int
    crs_rasterio: rasterio.CRS

    def __init__(
        self,
        data_cube_root: Union[str, Path],
        parameter_files: Optional[List[Union[str, Path]]] = None,
        citeme_path: Optional[Union[str, Path]] = None,
        provenance_path: Optional[Union[str, Path]] = None,
        logs_path: Optional[Union[str, Path]] = None,
    ) -> None:
        """
        Parses a datacube-definition.prj file from a datacube generated by FORCE.
        The structure of the file is explained in the FORCE documentation:
        https://force-eo.readthedocs.io/en/latest/howto/datacube.html#where-is-the-datacube-definition-stored

        :param data_cube_root: root directory of the datacube,
            the directory that contains the datacube-definition.prj file.
        """
        self._data_cube_root = Path(data_cube_root).resolve()
        self._parameter_files = (
            [Path(p).resolve() for p in parameter_files] if parameter_files else None
        )
        self.data_cube_definition_path = (
            self._data_cube_root / self.DATACUBE_DEFINITION_FILENAME
        )
        self._citeme_path = Path(citeme_path).resolve() if citeme_path else None
        self.provenance_path = Path(provenance_path) if provenance_path else None
        self.logs_path = Path(logs_path) if logs_path else None

        if not self._data_cube_root.exists():
            raise ValueError(f"Path to datacube '{data_cube_root}' does not exist")
        if not self._data_cube_root.exists():
            raise ValueError(f"Path to datacube '{data_cube_root}' does not exist")
        with open(self.data_cube_definition_path) as fp:
            self.projection_wkt = self._parse_data_cube_definition_entry(fp.readline())
            self.grid_origin_lon = float(
                self._parse_data_cube_definition_entry(fp.readline())
            )
            self.grid_origin_lat = float(
                self._parse_data_cube_definition_entry(fp.readline())
            )
            self.grid_origin_x = float(
                self._parse_data_cube_definition_entry(fp.readline())
            )
            self.grid_origin_y = float(
                self._parse_data_cube_definition_entry(fp.readline())
            )
            self.tile_size = int(
                float(self._parse_data_cube_definition_entry(fp.readline()))
            )
            self.block_size = int(
                float(self._parse_data_cube_definition_entry(fp.readline()))
            )
        self.crs_rasterio = rasterio.CRS.from_wkt(self.projection_wkt)
        self.layout_strategy = pystac.layout.CustomLayoutStrategy(
            item_func=lambda item, parent: Path(parent) / f"{item.id}.json"
        )

    def compute_bounding_box(self) -> shapely.Polygon:
        tiles = list(self.iter_tiles())
        tile_x = [int(t[1:5]) for t in tiles]
        tile_y = [int(t[7:11]) for t in tiles]

        return self._compute_bounding_box(
            min(tile_x), max(tile_x), min(tile_y), max(tile_y)
        )

    def _compute_bounding_box(
        self, min_tile_x: int, max_tile_x: int, min_tile_y: int, max_tile_y: int
    ) -> shapely.Polygon:
        target_crs = rasterio.CRS.from_string(self.TARGET_BOUNDS_CRS)
        left_proj = self.grid_origin_x + min_tile_x * self.tile_size
        right_proj = self.grid_origin_x + (max_tile_x + 1) * self.tile_size
        top_proj = self.grid_origin_y - min_tile_y * self.tile_size
        bottom_proj = self.grid_origin_y - (max_tile_y + 1) * self.tile_size
        west, south, east, north = warp.transform_bounds(
            self.crs_rasterio,
            target_crs,
            left=left_proj,
            bottom=bottom_proj,
            right=right_proj,
            top=top_proj,
            densify_pts=self.DENSIFY_POINTS_DEFAULT,
        )

        bounding_box = shapely.geometry.box(
            minx=west,
            maxy=south,
            maxx=east,
            miny=north,
        )

        return bounding_box

    @staticmethod
    def _parse_data_cube_definition_entry(line) -> str:
        entry = line.split("=")[-1].strip()
        return entry

    def iter_tiles(self) -> Iterable[str]:
        return (t.name for t in self._data_cube_root.glob("X????_Y????"))

    def iter_asset_paths(self, tile) -> Iterable[Path]:
        return (self._data_cube_root / tile).iterdir()

    def get_relative_path(self, abs_path: Union[str, Path]) -> Path:
        abs_path: Path = Path(abs_path)
        return abs_path.relative_to(self._data_cube_root)

    def get_parameter_files(self) -> Optional[Iterable[Path]]:
        return self._parameter_files
