from pathlib import Path

class ForceDataCubeDefinition:
    DATACUBE_DEFINITION_FILENAME = "datacube-definition.prj"
    def __init__(self, data_cube_root: Path):
        """
        Parses a datacube-definition.prj file from a datacube generated by FORCE.
        The structure of the file is explained in the FORCE documentation:
        https://force-eo.readthedocs.io/en/latest/howto/datacube.html#where-is-the-datacube-definition-stored

        :param data_cube_root: root directory of the datacube,
            the directory that contains the datacube-definition.prj file.
        """
        self._data_cube_root = data_cube_root
        with open(data_cube_root / self.DATACUBE_DEFINITION_FILENAME) as fp:
            self.projection_wkt = fp.readline().strip()
            self.grid_origin_lon = fp.readline().strip()
            self.grid_origin_lat = fp.readline().strip()
            self.grid_origin_x = fp.readline().strip()
            self.grid_origin_y = fp.readline().strip()
            self.tile_size = fp.readline().strip()
            self.block_size = fp.readline().strip()


def bounding_box_from_datacube_definition(datacube_definition):
    pass
