from typing import Dict, Optional
from collections.abc import Callable

from pathlib import Path

# TODO replace rasterio with pyproj
import rasterio
import shapely
from rasterio import warp
import click


@click.command()
@click.argument("data_cube_root", type=click.Path(exists=True))
def compute_datacube_bounding_box(data_cube_root):
    data_cube_def = ForceDataCubeDefinition(data_cube_root)
    bounding_box = data_cube_def.compute_bounding_box()

    bounding_box_shapely = shapely.geometry.box(
        minx=bounding_box["west"],
        maxy=bounding_box["south"],
        maxx=bounding_box["east"],
        miny=bounding_box["north"],
    )

    import pdb
    pdb.set_trace()
    print(bounding_box_shapely.wkt)


class ForceDataCubeDefinition:
    DATACUBE_DEFINITION_FILENAME: str = "datacube-definition.prj"
    TARGET_BOUNDS_CRS: str = "EPSG:4326"
    DENSIFY_POINTS_DEFAULT: int = 21

    _data_cube_root: Path|str
    projection_wkt: str
    grid_origin_lon: float
    grid_origin_lat: float
    grid_origin_x: float
    grid_origin_y: float
    tile_size: int
    block_size: int
    crs_rasterio: rasterio.CRS

    def __init__(self, data_cube_root: Path|str):
        """
        Parses a datacube-definition.prj file from a datacube generated by FORCE.
        The structure of the file is explained in the FORCE documentation:
        https://force-eo.readthedocs.io/en/latest/howto/datacube.html#where-is-the-datacube-definition-stored

        :param data_cube_root: root directory of the datacube,
            the directory that contains the datacube-definition.prj file.
        """
        self._data_cube_root = Path(data_cube_root)
        with open(self._data_cube_root / self.DATACUBE_DEFINITION_FILENAME) as fp:
            self.projection_wkt = self._parse_data_cube_definition_entry(fp.readline())
            self.grid_origin_lon = self._parse_data_cube_definition_entry(fp.readline(), float)
            self.grid_origin_lat = self._parse_data_cube_definition_entry(fp.readline(), float)
            self.grid_origin_x = self._parse_data_cube_definition_entry(fp.readline(), float)
            self.grid_origin_y = self._parse_data_cube_definition_entry(fp.readline(), float)
            self.tile_size = int(self._parse_data_cube_definition_entry(fp.readline(), float))
            self.block_size = int(self._parse_data_cube_definition_entry(fp.readline(), float))
        self.crs_rasterio = rasterio.CRS.from_wkt(self.projection_wkt)

    def compute_bounding_box(self) -> Dict[str, float|str]:
        tiles = [t.name for t in  self._data_cube_root.glob("X????_Y????")]
        tile_x = [int(t[1:5]) for t in tiles]
        tile_y = [int(t[7:11]) for t in tiles]

        return self._compute_bounding_box(min(tile_x), max(tile_x), min(tile_y), max(tile_y))

    def _compute_bounding_box(self, min_tile_x: int, max_tile_x: int, min_tile_y: int, max_tile_y: int) -> Dict[str, float|str]:
        target_crs = rasterio.CRS.from_string(self.TARGET_BOUNDS_CRS)
        left_proj = self.grid_origin_x + min_tile_x * self.tile_size
        right_proj = self.grid_origin_x + (max_tile_x + 1) * self.tile_size
        top_proj = self.grid_origin_y - min_tile_y * self.tile_size
        bottom_proj = self.grid_origin_y - (max_tile_y + 1) * self.tile_size
        west, south, east, north = warp.transform_bounds(
            self.crs_rasterio,
            target_crs,
            left=left_proj,
            bottom=bottom_proj,
            right=right_proj,
            top=top_proj,
            densify_pts=self.DENSIFY_POINTS_DEFAULT
        )

        # TODO better box type?
        return {
            "west": west,
            "south": south,
            "east": east,
            "north": north,
            "crs": target_crs.to_wkt(),
        }

    @staticmethod
    def _parse_data_cube_definition_entry(line, dtype: Optional[Callable]=None):
        entry = line.split("=")[-1].strip()
        if dtype:
            return dtype(entry)
        return entry



def bounding_box_from_datacube_definition(datacube_definition):
    pass
