---
format:
    html:
        code-fold: false
        page-navigation: true
execute:
    freeze: true
---

# Parametrization

The [FORCE openEO processes](processes.qmd) (`force_level2` and `force_tsa`) accept most of the parameters that can be passed using FORCE's native parametrization files ([level 2](https://force-eo.readthedocs.io/en/latest/components/lower-level/level2/param.html), [TSA](https://force-eo.readthedocs.io/en/latest/components/higher-level/tsa/param.html)). The exceptions to this rule are explained below.

There are 4 types of parameters that do not correspond exactly to the FORCE parameter files 

1. Special parameters that require translation (e.g., the area of interest)
1. Additional parameters of the openEO integration (e.g., the processing name)
1. FORCE parameters that are not exposed through the openEO API (e.g., the number of processes used for processing)
1. Parameters that support only a subset of the possible values

Parameter names follow the openEO convention and have `snake_case`. Otherwise, the names are unchanged from those of the original parameter files.
It is possible to inspect the processes (and see their parameters) using openEO's [`describe_process`](https://open-eo.github.io/openeo-python-client/api.html#openeo.rest.connection.Connection.describe_process) method. See [processes.qmd] for more.

Parameter values may be strings (the same as in FORCE parameter files) or native python values which can be serialized to JSON. Values are converted to UPPERCASE before being passed into the parameter file.

Parameter values are passed as a dictionary to the `arguments` parameter of `openeo.processes.process`:


```{.python}
graph = openeo.processes.process(
    process_id="force_level2",
    arguments=dict(
        stac_document=stac_catalog,
        name="Modena",
        do_brdf=True,
        # ... <--- more parameters
    }
)

```

## Examples

| FORCE parameter file | openEO |
|----------------------|--------|
| `PROJECTION = GLANCE7` | `projection = GLANCE7`|
| `DO_BRDF = TRUE`  | `do_brdf=True`
| `CLOUD_THRESHOLD = 0.225` | `cloud_threshold=0.255`

## FORCE Level 2

### Special parameters

- `aoi`: replaces the `FILE_AOI` parameter. Pass a geojson feature (instead of a shapefile). See also [the aoi parameter description of level2](level2.qmd#Area of extent)
- `dem`: replaces digital elevation model specific parameters (`FILE_DEM`, `DEM_RESAMPLING`, `DEM_NODATA`). Only possible value is `Copernicus_30m`

### openEO specific parameters

:::{.callout-tip}
Check out the [FORCE level 2](level2.qmd) section of the guide to learn more about selecting and passing inputs.
:::

- `stac_document` and `stac_url`: STAC documents describing the input products. Can be either an URL `stac_url` or the content (`stac_document` as a dictionary) of a STAC document. One of these parameters must be set.
- `name`: Give a name to the FORCE processing task. Determines the name of the STAC item describing the output data cube.

### Partially supported parameters

- `projection`: Only GLANCE7 (the default) is tested.
- `output_format`: Supports `GTiff`, `COG`

### Unsupported parameters

Input/Output directories (managed by the integration)

- `FILE_QUEUE`
- `DIR_LEVEL2`
- `DIR_LOG`
- `DIR_PROVENANCE`
- `DIR_TEMP`

Parallel processing parameters (managed by the integration)

- `NPROC` 
- `NTHREAD`
- `PARALLEL_READS`
- `DELAY`
- `TIMEOUT_ZIP`

## FORCE Time Series Analysis

### Special parameters

### openEO specific parameters

### Partially supported parameters

- `output_format`: Supports `GTiff`, `COG`
- `target_sensor`: Supports Sentinel-2 types:
    - SEN2A
    - SEN2B
    - SEN2C
    - SEN2L


### Unsupported parameters

Input/Output directories (managed by the integration)

- `DIR_LOWER`
- `DIR_HIGHER`
- `DIR_PROVENANCE`
- `DIR_MASK`

Masking

- `DIR_MASK`
- `BASE_MASK`
- `READ_ERROR_MASK`

Output Options

- `FILE_OUTPUT_OPTIONS`

Parallel processing (managed by the integration)

- `NTREHAD_READ`
- `NTHREAD_COMPUTE`
- `NTHREAD_WRITE`
- `STREAMING` (TRUE)
- `PRETTY_PROGRESS`

Extent

- `FILE_TILE`


Spectral Mixture Analysis

- `FILE_ENDMEM` (NULL)
- `SMA_SUM_TO_ONE`
- `SMA_NON_NEG`
- `SMA_SHD_NORM`
- `SMA_ENDMEMBER`
- `OUTPUT_RMS`

Python UDFs

- `FILE_PYTHON`
- `PYTHON_TYPE`
- `OUTPUT_PYP`

R UDFs

- `FILE_RSTATS`
- `RSTATS_TYPE`
- `OUTPUT_RSP`
