style {
    fill: transparent
}
(*** -> ***)[*]: {
    style {
        stroke-width: 6
        font-size: 30
        stroke: "#111F3D"
        font-color: black
    }
}
(*** <- ***)[*]: {
    style {
        stroke-width: 6
        font-size: 30
        stroke: "#47B149"
        font-color: white
    }
}

vars: {
 d2-config: {
    layout-engine: ELK
 }
}
direction: right

classes: {
    workflow: {
        style: {
            font-size: 30
            fill: "#EAC868"
            border-radius: 10
        }
    }
    CLT: {
        style {
            fill:  "#f7e9c3"
            font-size: 30
            border-radius: 10
        }
    }
    script: {
        style {
            fill: "#B5E0B6"
            font-size: 30
        }
    }
    force: {
        style {
            fill: "#47B149"
            font-size: 30
            #font-color: white
        }
    }
    group: {
        style {
            fill: "#BCE6F8"
            font-size: 30
        }
    }
    main: {
        style {
            fill:  "#21ACE9"
            bold: true
            font-size: 40
        }
    }
}


eoap {
    label: Force EOAP 
    class: main
    Docker {
        class: group
        force {
            class: force
            label: FORCE (base image)
        }
        l2-wrapper {
            class: script
            label: "Wrapper: Level 2"
        }
        tsa-wrapper {
            class: script
            label: "Wrapper: TSA"
        }
    }
    CWL {
        class: group
        label: "CWL description"
        l2-wf {
            label: FORCE Level 2 Workflow
            class: workflow
        }
        tsa-wf {
            label: FORCE TSA Workflow
            class: workflow
        }
        l2-clt {
            label: FORCE Level 2 CommandLineTool 
            class: CLT
        }
        staging-clt {
            label: Staging CommandLineTool
            class: CLT
        }
        tsa-clt {
            label: FORCE TSA CommandLineTool
            class: CLT
        }
        tsa-wf -> tsa-clt
        tsa-wf -> staging-clt
        l2-wf -> l2-clt
        l2-wf -> staging-clt
    }
}

eoap.cwl.l2-clt -> eoap.docker: references
eoap.cwl.tsa-clt -> eoap.docker: references
