name: Test Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Create as pre-release'
        required: false
        type: boolean
        default: false

jobs:
  python-tests:
    uses: ./.github/workflows/python-tests.yml

  integration-tests-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'python/.python-version'
      - name: Set up UV
        uses: astral-sh/setup-uv@v7
      - name: Get release version
        run: |
          RELEASE_VERSION=$({{ github.ref_name }} | sed 's/v//' | tr -d '\n')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Info
        run: |
          echo {{ env.RELEASE_VERSION }}
      - name: Check versions
        run: |
          # Fails if versions in pyproject.toml, cwl/docker-requirement.yaml and the reference given
          # do not match
          ./tools/check-version-matches.sh {{ env.RELEASE_VERSION }}
          # Fails if lock file is out of date
          uv lock --project python --locked
      - name: download input products from lfs
        run: |
          git lfs install
          git lfs pull --include="test/data/S2A_MSIL1C_20260310T101051_N0512_R022_T32TPQ_20260310T152637.SAFE.zip"
          unzip test/data/*.SAFE.zip -d ../inputs
      - name: FORCE level 2 test
        id: force_level2_test
        run: |
          uv run --with cwltool bash test/test_force_level2_cltool.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.EODATA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.EODATA_AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: https://eodata.dataspace.copernicus.eu
          S3_ENDPOINT_URL: https://eodata.dataspace.copernicus.eu
      - name: FORCE TSA test
        id: force_tsa_test
        run: |
          uv run --with cwltool bash test/test_force_tsa_cltool.sh
      - name: Generate Full Workflow files
        run: |
          uv run --with cwltool tools/compile-workflows.sh "."
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            force-level2.cwl
            force-tsa.cwl
            README.md
            LICENSE
            CHANGELOG.md
          prerelease: ${{ github.event.inputs.prerelease || false }}
